title: Branden Isadia
email: brandenisadia@gmail.com
show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
minima:
  skin: dark

markdown: kramdown

url: "https://branden254.github.io/"
baseurl: "YoutubeAnalysis/"
gem "github-pages", group: :jekyll_plugins

github_username: branden254
